# -*- coding: utf-8 -*-
"""SparkRDD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13FisX3hxIfQZHAR7NjVUWiEWvxgsNmaC
"""

print("Hello")
from pyspark import Sparkcontext
sc = SparkContext()

xyz = sc.parallelize([1,2,3,3,4,4],8)

print(type(xyz))
print("Something")
print(xyz)
type(xyz)

xyz.collect()

xyz.take(5)

xyz.first()

xyz.count()

xyz.getNumPartitions()

abc = xyz.coalesce(2)
abc.getNumPartitions()

rama = xyz.repartition(41)
rama.getNumPartitions()

words = sc.parallelize(["hadoop", "spark", "sparkscala", "java"])
words_filter = words.filter(lambda x: 'spark' in x)
words_filter.collect()

words.getNumPartitions()

myrdd = words.map(lambda x: (x,1))
myrdd.collect()

pq = sc.parallelize(["red","green", "blue","red","green", "yellow"])

pqr = pq.map(lambda x: (x,1))

myresults = pqr.reduceByKey(lambda x,y: (x+y))
myresults.collect()

myresults.getNumPartitions()

myresults.saveAsTextFile('/content/sample_data/myresult')
myresults.coalesce(1).saveAsTextFile('/content/sample_data/myresult1')

# flatmap
xyz = ["rama laxman", "iam in hyd","where r you","going to office for doing job"]

myrdd = sc.parallelize(xyz)
myrdd.take(5)

myxyz = myrdd.flatMap(lambda x:x.split(" "))
myxyz.collect()

wpfile = sc.textFile('/content/war_and_peace.txt',4)

type(wpfile)

wpfile.take(5) # unstructured data

wpfile.getNumPartitions()

wpfile.count()

wpfile.cache()

# find the word count ?
myxyz = wpfile.flatMap(lambda x: x.split(" "))
myxyz = myxyz.map(lambda x: x.lower())
myxyz.take(3)

myxyz1 = myxyz.map(lambda x: (x,1))
myxyz1.take(30)

mycount = myxyz1.reduceByKey(lambda x,y: x+y)
mycount.take(10)

mycount.saveAsTextFile('/content/output_war_and_peace.txt')

mycount.take(3)

wpfile.take(3)

moviesrdd = sc.textFile('/content/movies.csv')

moviesrdd.count()

moviesrdd.cache()
moviesrdd.take(11)

ratingsrdd = sc.textFile('/content/ratings.csv',4)
print(ratingsrdd.getNumPartitions())
print(ratingsrdd.count())
ratingsrdd.take(5)

# removing the column names
moviesData = moviesrdd.filter(lambda line: not line.startswith('movieId'))
moviesData.take(10)

ratingsData = ratingsrdd.filter(lambda x: not x.startswith('userId'))
ratingsData.take(10)

movies_by_movieId = moviesData\
.map(lambda x: x.split(','))\
.map(lambda tokens: (int(tokens[0]),tokens[1]))

movies_by_movieId.first()

ratings_by_movie_id = ratingsData\
.map(lambda x: x.split(','))\
.map(lambda tokens: (int(tokens[1]), float(tokens[2])))
ratings_by_movie_id.take(3)

df_movies = movies_by_movieId.join(ratings_by_movie_id).take(10)

"""## find out the top 10 movies based on highest average rating. Consider only those movies that have got at least 100 ratings."""

df_movies = df_movies.map(lambda x: (x,1))
df_movies

print("Hello")